name: student_marker
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'


dependencies:
  build_runner: ^2.4.6
  nearby_connections: ^4.0.1
  flutter_bloc: ^8.1.3
  auto_size_text: ^3.0.0
  flutter_styled_toast: ^2.2.1
  bloc: ^8.1.2
  freezed: ^2.4.3
  get_it: ^7.6.4
  shared_preferences: ^2.2.1
  flutter_native_splash: ^2.3.2
  flutter_gen: 5.3.2
  device_preview: ^1.1.0
  device_information: ^0.0.4
  permission_handler: ^11.0.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/picture/student_icon.png

  android_12:
    image: assets/picture/student_icon.png
    icon_background_color: "#ffffff"



  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: 0.13.1


flutter:

  uses-material-design: true

  assets:
    - assets/picture/

  fonts:
    - family: RubikDistressed
      fonts:
        - asset: assets/fonts/RubikDistressed-Regular.ttf
          style: italic

